CREATE TABLE [dbo].[Mayor_Seafood] (
    [mayorId]   INT NOT NULL,
    [seafoodId] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([mayorId] ASC, [seafoodId] ASC)
);

INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (1, N'abalone')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (2, N'acorn barnacle')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (3, N'chambered nautilus')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (4, N'clam')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (5, N'ear shell')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (6, N'flatworm')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (7, N'giant isopod')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (8, N'horsehair crab')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (9, N'horseshoe crab')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (10, N'lobster')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (11, N'mantis shrimp')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (12, N'octopus')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (13, N'oyster')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (14, N'pearl oyster')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (15, N'red king crab')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (16, N'scallop')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (17, N'sea anemone')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (18, N'sea cucumber')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (19, N'sea grapes')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (20, N'sea slug')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (21, N'sea star')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (22, N'sea urchin')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (23, N'seaweed')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (24, N'snow crab')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (25, N'spider crab')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (26, N'spiny lobster')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (27, N'spotted garden eel')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (28, N'sweet shrimp')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (29, N'tiger prawn')
INSERT INTO [dbo].[Seafood] ([seafoodId], [seafoodName]) VALUES (30, N'turban shell')
